### ISSUE TITLE
Is this application hosted somewhere?

### ISSUE THREAD

**Issue by KamarajuKusumanchi** [draghuram/musicalbingo#1]
Just wondering if you have this application hosted as a website somewhere?

**Comment by draghuram** [comment]
It is currently available at
    http://draghuram1.pythonanywhere.com/
though it is not guaranteed to exist for very  long time. If really required, the code is really simple and can be run locally. Thanks.

**Comment by KamarajuKusumanchi** [comment]
Thanks! It looks very nice!
